#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
screw_head_pcd.py
~~~~~~~~~~~~~~~~~
    * 生成螺丝头（槽形可选）顶面点云
    * 按面积均匀采样
    * 保存为 PLY（ASCII / binary）
    * 可视化散点图

Author : ChatGPT (2025-06-10)
"""

import numpy as np
import argparse
import struct
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D   # noqa: F401  (needed for 3-D projection)


# ----------------------------------------------------------------------
# 1) 生成顶面高度网格
# ----------------------------------------------------------------------
def generate_top_face_multi_gaussian(n=40, bumps=None, cube_size=1.0):
    if bumps is None:
        bumps = []

    xs = np.linspace(0, cube_size, n)
    ys = np.linspace(0, cube_size, n)

    vertices = []
    for y in ys:
        for x in xs:
            z = cube_size
            for bump in bumps:
                A, x0, y0, sigma = bump["A"], bump["x0"], bump["y0"], bump["sigma"]
                z += A * np.exp(-((x - x0) ** 2 + (y - y0) ** 2) / (2 * sigma ** 2))
            vertices.append([x, y, z])

    vertices = np.asarray(vertices, dtype=np.float32)

    # 每个小网格 → 两个三角形
    triangles = []
    for j in range(n - 1):
        for i in range(n - 1):
            idx0 = j * n + i
            idx1 = j * n + i + 1
            idx2 = (j + 1) * n + i
            idx3 = (j + 1) * n + i + 1
            triangles.append([idx0, idx1, idx2])
            triangles.append([idx2, idx1, idx3])

    triangles = np.asarray(triangles, dtype=np.int32)
    return vertices, triangles


# ----------------------------------------------------------------------
# 2) 网格表面按面积均匀采样
# ----------------------------------------------------------------------
def sample_points_on_mesh(vertices: np.ndarray,
                          triangles: np.ndarray,
                          n_points: int) -> np.ndarray:
    v0 = vertices[triangles[:, 0]]
    v1 = vertices[triangles[:, 1]]
    v2 = vertices[triangles[:, 2]]

    # 三角形面积
    tri_vec = np.cross(v1 - v0, v2 - v0)
    areas = 0.5 * np.linalg.norm(tri_vec, axis=1)
    probs = areas / areas.sum()

    # 1. 按面积分布抽取三角形下标
    tri_idx = np.random.choice(len(areas), size=n_points, p=probs)

    # 2. 每个三角形内用重心坐标均匀采样
    r1 = np.sqrt(np.random.rand(n_points))
    r2 = np.random.rand(n_points)
    u = 1 - r1
    v = r1 * (1 - r2)
    w = r1 * r2

    pts = (
        u[:, None] * v0[tri_idx] +
        v[:, None] * v1[tri_idx] +
        w[:, None] * v2[tri_idx]
    )
    return pts.astype(vertices.dtype)          # (N, 3)


# ----------------------------------------------------------------------
# 3) 生成螺丝头点云
# ----------------------------------------------------------------------
def screw_head_point_cloud(shape_id: int,
                           n_points: int = 2048,
                           n_grid: int = 40,
                           cube_size: float = 1.0,
                           depth: float = -0.15) -> np.ndarray:
    """
    Parameters
    ----------
    shape_id : 0 → slot（一字槽）, 1 → cross（十字槽）
    """
    if shape_id not in (0, 1):
        raise ValueError("shape_id must be 0 (slot) or 1 (cross).")

    if shape_id == 0:      # 一字槽
        bumps = [{
            "A": depth,
            "x0": cube_size / 2,
            "y0": cube_size / 2,
            "sigma": cube_size / 6
        }]
    else:                   # 十字槽
        c, s = cube_size / 2, cube_size / 6
        bumps = [
            {"A": depth, "x0": c, "y0": c - 0.25 * c, "sigma": s},
            {"A": depth, "x0": c, "y0": c + 0.25 * c, "sigma": s},
            {"A": depth, "x0": c - 0.25 * c, "y0": c,            "sigma": s},
            {"A": depth, "x0": c + 0.25 * c, "y0": c,            "sigma": s},
        ]

    verts, tris = generate_top_face_multi_gaussian(n=n_grid,
                                                   bumps=bumps,
                                                   cube_size=cube_size)
    return sample_points_on_mesh(verts, tris, n_points)


# ----------------------------------------------------------------------
# 4) 写入 PLY
# ----------------------------------------------------------------------
def write_ply(points: np.ndarray,
              filename: str,
              ascii: bool = True):
    """
    写入 PLY 文件，仅包含 xyz 三个 float
    ascii=True  → ASCII PLY
    ascii=False → binary_little_endian PLY
    """
    n = points.shape[0]
    header = (
        "ply\n"
        f"format {'ascii 1.0' if ascii else 'binary_little_endian 1.0'}\n"
        "comment generated by screw_head_pcd.py\n"
        f"element vertex {n}\n"
        "property float x\n"
        "property float y\n"
        "property float z\n"
        "end_header\n"
    )

    if ascii:
        with open(filename, "w") as f:
            f.write(header)
            np.savetxt(f, points, fmt="%.6f")
    else:
        with open(filename, "wb") as f:
            f.write(header.encode("utf-8"))
            # 按 <f4 格式二进制写入
            f.write(points.astype("<f4").tobytes())
    print(f"[✓] PLY saved to {filename} ({'ASCII' if ascii else 'binary'})")


# ----------------------------------------------------------------------
# 5) 可视化
# ----------------------------------------------------------------------
def visualize(points: np.ndarray, title: str = "Point cloud"):
    fig = plt.figure(figsize=(6, 6))
    ax = fig.add_subplot(111, projection="3d")
    ax.scatter(points[:, 0], points[:, 1], points[:, 2], s=1)
    ax.set_title(title)
    ax.set_xlabel("X")
    ax.set_ylabel("Y")
    ax.set_zlabel("Z")
    plt.tight_layout()
    plt.show()


# ----------------------------------------------------------------------
# 6) CLI
# ----------------------------------------------------------------------
def parse_args():
    parser = argparse.ArgumentParser(
        description="Generate screw-head point cloud & save to PLY")
    parser.add_argument("--shape", type=int, default=1,
                        help="0 = slot, 1 = cross (default 1)")
    parser.add_argument("--points", type=int, default=2048,
                        help="number of points (default 2048)")
    parser.add_argument("--grid", type=int, default=40,
                        help="grid resolution (default 40)")
    parser.add_argument("--cube", type=float, default=1.0,
                        help="cube size (default 1.0)")
    parser.add_argument("--depth", type=float, default=-0.15,
                        help="slot depth (default -0.15)")
    parser.add_argument("--out", type=str, default="screw_head.ply",
                        help="output PLY filename")
    parser.add_argument("--binary", action="store_true",
                        help="save as binary_little_endian PLY")
    parser.add_argument("--show", action="store_true",
                        help="show 3-D scatter plot")
    return parser.parse_args()


def main():
    args = parse_args()

    pcd = screw_head_point_cloud(
        shape_id=args.shape,
        n_points=args.points,
        n_grid=args.grid,
        cube_size=args.cube,
        depth=args.depth
    )

    write_ply(pcd, args.out, ascii=not args.binary)

    if args.show:
        shape_name = "Cross-slot" if args.shape else "Slot"
        visualize(pcd, f"{shape_name} screw head ({pcd.shape[0]} pts)")


if __name__ == "__main__":
    main()
